name: Build, test, package

on:
  push:
    branches:
      #- main           # Disabled for testing
      - dev

jobs:

  build:
    name: Ubuntu based build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install build tools
        run: >
          sudo apt-get install
            ninja-build
      - name: Build wask-sdk
        run: |
          cmake --version
          ninja --version
        #
        #run: >
        #  make -j $(nproc) build
        #    NINJA_FLAGS=-v
        #    PREFIX=

#
#  test:
#    name: "Test"
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Run the testsuite
#        run: NINJA_FLAGS=-v make check
#
#  package:
#    name: "Package"
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          # Upload the dist folder. Give it a name according to the OS it was built for.
#          name: ${{ format( 'dist-{0}', matrix.os) }}
#          path: dist

