name: "Build, test, release"

on:
  push:
    tags:
      - "wasi-sdk-*"
    branches:
#     - main
      # <DEBUG>
      - dev
      # </DEBUG>
  pull_request:

jobs:

  build_ubuntu:
    name: "Ubuntu"
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest

  build_macos:
    name: "macOS"
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: 
      - build_ubuntu
      - build_macos
    if: github.ref_type == 'tag'
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: ${{ format('dist-{0}', runner.os) }}
          path: dist
      - name: "Rename build artifacts"
        run: for file in dist/*.tar.gz; do mv $file ${file/.tar.gz/-${{runner.os}}-${{runner.arch}}.tar.gz}; done
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/*.tar.gz

