name: "Build, test, release"

on:
  push:
    tags:
      - "*"
    branches:
      #- main           # Disabled for testing

      # <DEBUG>
      - dev
      # </DEBUG>

jobs:

  build:
    name: "Build wasi-sdk"
    runs-on: ubuntu-20.04
    steps:
#     - name: "Checkout wasi-sdk repo"
#       uses: actions/checkout@v1     # >@v1 fails on submodules
#       with:
#         submodules: true
#     - name: "Install build tools"
#       run: sudo apt-get install ninja-build
#     - name: "Build wasi-sdk"
#       run: NINJA_FLAGS=-v PREFIX= make -j $(nproc) build
#     - name: "Upload wasi-sdk build"
#       uses: actions/upload-artifact@v3
#       with:
#         name: wasi-sdk
#         path: build/install

      # <DEBUG>
      - run: |
        echo "Event SHA: ${{github.event.after}}"
        echo "Building wasi-sdk"
      # </DEBUG>

  test:
    name: "Test wasi-sdk"
    runs-on: ubuntu-20.04
    needs: build
    steps:
#     - name: Run the testsuite
#       run: NINJA_FLAGS=-v make check

      # <DEBUG>
      - run: echo "Testing wasi-sdk"
      # </DEBUG>

  release:
    name: "Release wasi-sdk"
    runs-on: ubuntu-20.04
    needs: test
    if: >-
      contains(github.event_name, 'push')
      && contains(github.event.ref, 'refs/tags')
    steps:
#     - name: "Upload wasi-sdk artifacts"
#       uses: actions/upload-artifact@v3
#       with:
#         name: wasi-sdk-ubuntu-20.04
#         path: dist

      # <DEBUG>
      - run: echo "Creating release ${{github.ref}}"
      # </DEBUG>

