name: Build, test, publish

on:
  push:
    tags:
      - "*"
    branches:
      #- main           # Disabled for testing
      - dev

jobs:

# # Build wasi-sdk
# build:
#   name: "Build wasi-sdk"
#   runs-on: ubuntu-20.04
#   steps:
#     - name: "Checkout wasi-sdk repo"
#       uses: actions/checkout@v1     # >@v1 fails on submodules
#       with:
#         submodules: true
#     - name: "Install build tools"
#       run: sudo apt-get install ninja-build
#     - name: "Build wasi-sdk"
#       run: NINJA_FLAGS=-v PREFIX= make -j $(nproc) build
#     - name: "Upload wasi-sdk build"
#       uses: actions/upload-artifact@v3
#       with:
#         name: wasi-sdk
#         path: build/install

#test:
#  name: "Test wasi-sdk"
#  runs-on: ubuntu-20.04
#  steps:
#    - name: Run the testsuite
#      run: NINJA_FLAGS=-v make check


  publish:
    name: "Publish wasi-sdk"
#   needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: "Echo push to branch"
        if: contains(github.event_name, 'push') && contains(github.event.ref, 'refs/heads')
        run: echo "Event was push to branch (${{github.event.ref}})"
      - name: "Echo push tag"
        if: contains(github.event_name, 'push') && contains(github.event.ref, 'refs/tags')
        run: echo "Event was tag push (${{github.event.ref}})"
#     - name: "Upload wasi-sdk artifacts"
#       uses: actions/upload-artifact@v3
#       with:
#         name: wasi-sdk-ubuntu-20.04
#         path: dist

