name: "Build, test, release"

on:
  push:
    tags:
      - "wasi-sdk-*"
    branches:
#     - main
      # <DEBUG>
      - dev
      # </DEBUG>
  pull_request:

jobs:

  build_ubuntu:
    name: "Ubuntu"
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest

  build_macos:
    name: "macOS"
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: 
      - build_ubuntu
      - build_macos
    if: github.ref_type == 'tag'
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
#     - name: "Rename build artifacts"
#       run: for file in dist-*/*.tar.gz; do mv $file ${file/.tar.gz/_${{runner.arch}}.tar.gz}; done
      - run: ls -R dist-*
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist-ubuntu-latest/*.tar.gz
            dist-macos-latest/*.tar.gz

