name: "Build, test, release"

on:
  push:
    tags:
      - "wasi-sdk-*"
    branches:
#     - main
      # <DEBUG>
      - dev
      # </DEBUG>
  pull_request:

jobs:

  build_ubuntu_x64:
    name: "Ubuntu"
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      arch: x64

  build_macos_x64:
    name: "macOS"
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
      arch: x64

  build_windows_x64:
    name: "Windows"
    uses: ./.github/workflows/build.yml
    with:
      os: windows-2019        # vcvarsall.bat requires Visual Studio 2019
      arch: x64

# build_windows_x86:
#   name: "Windows"
#   uses: ./.github/workflows/build.yml
#   with:
#     os: windows-2019        # vcvarsall.bat requires Visual Studio 2019
#     arch: x86               # Cross-compilation

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: 
      - build_ubuntu_x64
      - build_macos_x64
      - build_windows_x64
#     - build_windows_x86
    if: github.ref_type == 'tag'
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
      - name: "Rename build artifacts"
        run: for file in dist-*/*.tar.gz; do mv $file ${file/.tar.gz/_${{runner.arch}}.tar.gz}; done
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist-*/*.tar.gz

