name: "Build, test, release"

on:
  push:
    tags:
      - "wasi-sdk-*"
    branches:
#     - main
      # <DEBUG>
      - dev
      # </DEBUG>
  pull_request:

jobs:

  build_ubuntu:
    name: "Ubuntu"
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest

  build_macos:
    name: "macOS"
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest

  build_windows:
    name: "Windows"
    uses: ./.github/workflows/build.yml
    with:
      os: windows-2019

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: 
      - build_ubuntu
      - build_macos
      - build_windows
    if: github.ref_type == 'tag'
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
      - name: "Rename build artifacts"
        run: for file in dist-*/*.tar.gz; do mv $file ${file/.tar.gz/_${{runner.arch}}.tar.gz}; done
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist-*/*.tar.gz

