name: "Build, test, release"

on:
  push:
    tags:
      - "*"
    branches:
#     - main
      # <DEBUG>
      - dev
      # </DEBUG>

jobs:

  build:
    name: "Build wasi-sdk"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v1     # >@v1 fails on submodules
#       with:
#         submodules: true
#     - name: "Install build tools"
#       run: sudo apt-get install ninja-build
#     - name: "Build and package"
#       run: NINJA_FLAGS=-v PREFIX= make -j $(nproc) package
      # <DEBUG>
      - run: |
          echo "Build and package"
          mkdir dist
          touch dist/wasi-sdk-$(./version.sh)-linux.tar.gz
          touch dist/libclang_rt.builtins-wasm32-wasi-$(./version.sh).tar.gz
          touch dist/wasi-sysroot-$(./version.sh).tar.gz
      # </DEBUG>
      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: ${{format('dist-{0}',matrix.os)}}

  test:
    name: "Test wasi-sdk"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
      fail-fast: false
    runs-on: ${{matrix.os}}
    needs: build
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v1     # >@v1 fails on submodules
        with:
          submodules: false
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: ${{format('dist-{0}',matrix.os)}}
          path: dist
#     - name: "Extract build artifacts"
#       run: tar -xvzf dist/wasi-sdk-$(./version.sh)-linux.tar.gz
#     - name: "Install build artifacts"
#       run: >-
#         mkdir build
#         && mv wasi-sdk-$(./version.sh)-linux build/install
#     - name: "Run test suite"
#       run: >-
#         NINJA_FLAGS=-v PREFIX= make -j $(nproc) check
      # <DEBUG>
      - run: |
          echo "Run test suite"
          ls -R
      # </DEBUG>

  release:
    name: "Release wasi-sdk"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
      fail-fast: false
    runs-on: ${{matrix.os}}
    needs: test
    if: >-
      contains(github.event_name, 'push')
      && contains(github.event.ref, 'refs/tags')
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v1     # >@v1 fails on submodules
        with:
          submodules: false
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          draft: true
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: ${{format('dist-{0}',matrix.os)}}
          path: dist
      - name: "Upload wasi-sdk artifact"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/wasi-sdk-$(./version.sh)-linux.tar.gz
          asset_name: wasi-sdk.tar.gz
          asset_content_type: application/x-gtar
      - name: "Upload libclang_rt artifact"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/libclang_rt.builtins-wasm32-wasi-$(./version.sh).tar.gz
          asset_name: libclang_rt.tar.gz
          asset_content_type: application/x-gtar
      - name: "Upload wasi-sysroot artifact"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/wasi-sysroot-$(./version.sh).tar.gz
          asset_content_type: application/x-gtar


